### ISSUE TITLE
crash for legacy node.js version 0.10.xx

### ISSUE THREAD

**Issue by syarul** [Bartozzz/basic-collection#1]
You should support the collection to run on legacy node.js and legacy browser (i.e compiling it with babel)

```
const filter = require( "./filters.js" );
^^^^^
```

**Comment by Bartozzz** [comment]
It was made to be compatible with recent versions of `Node.js`. I'll try to add `0.x` support as soon as possible.

**Comment by Bartozzz** [comment]
Should work right now.
